In [8]:
import os
import mne
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xlrd
import pickle

In [33]:
with open('behavFiles/sent_dictionary.pkl', 'rb') as f:
    sentDict = pickle.load(f)

In [144]:
# Load behavioural file
behav_file = pd.read_csv( 'behavFiles/final_behavioral_file.csv' )

In [181]:
partList1 =['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16']
partList2 = ['21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33']
taskList = ['LT', 'MT', 'DT']

In [185]:
def load_sheet( part_num, task, file_name = 'behavFiles/SYMUL_stimulus_presentation.xls' ):
    if partNum == '16' and task == 'DT':
        sheet = 'Ep' + part_num + '_' + task
    elif partNum == '05' and task == 'LT':
        sheet = 'EP' + part_num  + task
    else:
        sheet = 'EP' + part_num + '_' + task
    df = pd.read_excel(io=file_name, sheet_name=sheet, engine='xlrd')
    return df

In [186]:
def extract_sents( df, part_num, task ):
    sentOrderList = []
    condList = []
    
    for i in range( 288 ):
        wordList = []
        for n in range( 6, 24 ):
            item = df.iloc[i,n]
            if isinstance( item, str ):
                wordList.append(item.strip('\"'))
                
        sentOrderList.append( " ".join(wordList) )
        condList.append( df.iloc[i,27].strip('\"') )
    
    output_df = pd.DataFrame({'part': part_num, 'sent': sentOrderList, 'cond': condList, 'task': task})

    return output_df

In [187]:
sentences_df = pd.DataFrame( columns=['part', 'sent', 'cond', 'task'] )

for task in taskList:
    for partNum in partList1:            
        load_df = load_sheet( partNum, task )
        single_df = extract_sents( load_df, partNum, task )

        sentences_df = pd.concat( [sentences_df, single_df] )

In [188]:
sentences_df.reset_index( drop=True, inplace=True )

In [189]:
sentences_df

      part                                               sent cond task
0       01  Daar staan de docenten die de grote toets verg...  EII   LT
1       01  De leerlingen is door het moeilijke voorval ge...  FII   LT
2       01           De bazin is door een blunder afgetreden.  FCC   LT
3       01       De inwoonster is naar het buurland gevlucht.  FCC   LT
4       01  De slordige klanten zijn alle bonnetjes kwijtg...  FCC   LT
...    ...                                                ...  ...  ...
13819   16  De jonge vrouwen is na het drukke feest afgedr...  FII   DT
13820   16  Daar komen de buurmannen die vroeger bijna ver...  ECC   DT
13821   16  De slanke tantes zijn door een streng dieet af...  FCI   DT
13822   16  Daar komt de getrainde hond die over het sloot...  EII   DT
13823   16  Daar komt de voorzichtige voetganger die de dr...  EII   DT

[13824 rows x 4 columns]

In [190]:
sentences_df.to_csv( 'behavFiles/sentLogs.csv', index=False )

In [199]:
symul1_nm = pd.read_csv( 'behavFiles/SYMUL1_M.csv', delimiter=';' )
symul1_nm[(symul1_nm['EPM#']=='EPM13')&(symul1_nm['Task']=='MT')&(symul1_nm['TRIAL']<108)]

      Task   EPM# Cond  Acc    RT      Time  TRIAL
10080   MT  EPM13  FII  hit  1318   4092020    101
10081   MT  EPM13  FCC  hit  1948   5922601    102
10082   MT  EPM13  FIC  hit  2121   1280753    103
10083   MT  EPM13  FII  hit  2132   6323973    104
10084   MT  EPM13  FII  hit  2134  15297769    105
10085   MT  EPM13  FII  hit  2183   2224118    106
10086   MT  EPM13  FCC  hit  2218  26234604    107